import React, { useEffect, useState, useMemo } from 'react';
import { collection, query, orderBy, onSnapshot, deleteDoc, doc } from 'firebase/firestore';
import { motion, AnimatePresence } from 'motion/react';
import { db } from '../../services/firebase';
import { useAuth } from '../../context/AuthContext';
import { ResumeAnalysis } from '../../types';
import { OperationType, handleFirestoreError } from '../../utils/error';
import { generatePDF } from '../../utils/pdfGenerator';
import { getScoreStyle } from '../../utils/scoreUtils';
import { Skeleton } from '../ui/Skeleton';
import {
  History,
  Search,
  SlidersHorizontal,
  Award,
  Calendar,
  Clock,
  Eye,
  Download,
  Trash2,
  FileText,
  Briefcase,
  AlertCircle,
  X,
  ArrowUpDown,
  Sparkles,
  FileDown,
} from 'lucide-react';

interface ResumeHistoryProps {
  onSelectAnalysis: (analysis: ResumeAnalysis) => void;
}

export const ResumeHistory: React.FC<ResumeHistoryProps> = ({ onSelectAnalysis }) => {
  const { user } = useAuth();
  const [history, setHistory] = useState<ResumeAnalysis[]>([]);
  const [loading, setLoading] = useState(true);

  // Search and Filter States
  const [searchQuery, setSearchQuery] = useState('');
  const [scoreFilter, setScoreFilter] = useState<'all' | 'high' | 'good' | 'low'>('all');
  const [sortBy, setSortBy] = useState<'newest' | 'oldest' | 'highest' | 'lowest'>('newest');
  const [deletingId, setDeletingId] = useState<string | null>(null);

  useEffect(() => {
    if (!user || !db) {
      setHistory([]);
      setLoading(false);
      return;
    }

    const path = `users/${user.uid}/analyses`;
    try {
      const q = query(collection(db, path), orderBy('createdAt', 'desc'));
      const unsubscribe = onSnapshot(
        q,
        (snapshot) => {
          const items: ResumeAnalysis[] = snapshot.docs.map((doc) => ({
            id: doc.id,
            ...(doc.data() as Omit<ResumeAnalysis, 'id'>),
          }));
          setHistory(items);
          setLoading(false);
        },
        (error) => {
          handleFirestoreError(error, OperationType.LIST, path);
          setLoading(false);
        }
      );

      return () => unsubscribe();
    } catch (err) {
      console.error('Error fetching history:', err);
      setLoading(false);
    }
  }, [user]);

  // Handle report download (.txt format)
  const handleDownloadReport = (item: ResumeAnalysis, e: React.MouseEvent) => {
    e.stopPropagation();
    const ats = item.atsScore ?? item.overallScore ?? 75;
    const name = item.resumeTitle || 'Resume_Evaluation';
    const uploadDate = new Date(item.createdAt).toLocaleDateString();
    const analysisDate = new Date(item.createdAt).toLocaleString();

    const reportText = `====================================================
RESUMEIQ - ATS RESUME ANALYSIS REPORT
====================================================
Resume Name: ${item.resumeTitle || 'Untitled Resume'}
Target Job Title: ${item.targetJobTitle || 'General Profile'}
Upload Date: ${uploadDate}
Analysis Date: ${analysisDate}
----------------------------------------------------
OVERALL ATS COMPATIBILITY SCORE: ${ats}/100
Grammar Score: ${item.grammarScore ?? 85}/100
Formatting Score: ${item.formattingScore ?? 80}/100
Readability Score: ${item.readabilityScore ?? 82}/100
Skills Score: ${item.skillsScore ?? 80}/100
----------------------------------------------------
EXECUTIVE SUMMARY:
${item.resumeSummary || item.summary || 'No summary available.'}

DETECTED SKILLS:
${(item.detectedSkills || item.keySkillsFound || []).map((s) => ` • ${s}`).join('\n') || ' None detected'}

RECOMMENDED / MISSING SKILLS:
${(item.missingSkills || []).map((s) => ` • ${s}`).join('\n') || ' None missing'}

DETECTED KEYWORDS:
${(item.detectedKeywords || []).map((k) => ` • ${k}`).join('\n') || ' None detected'}

MISSING ATS KEYWORDS:
${(item.missingKeywords || []).map((k) => ` • ${k}`).join('\n') || ' None missing'}

TOP STRENGTHS:
${(item.topStrengths || item.strengths || []).map((s) => ` • ${s}`).join('\n') || ' None listed'}

WEAKNESSES & AREAS TO IMPROVE:
${(item.weaknesses || []).map((w) => ` • ${w}`).join('\n') || ' None listed'}

EXPERIENCE FEEDBACK:
${item.experienceFeedback || 'N/A'}

PROJECT FEEDBACK:
${item.projectFeedback || 'N/A'}

EDUCATION FEEDBACK:
${item.educationFeedback || 'N/A'}

SUGGESTED ACTIONABLE TIPS:
${(item.improvedResumeTips || []).map((tip, idx) => ` ${idx + 1}. ${tip}`).join('\n') || ' N/A'}

====================================================
Report generated by ResumeIQ AI Platform
====================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${name.replace(/[^a-zA-Z0-9_-]/g, '_')}_ATS_Report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Handle PDF report generation
  const handleDownloadPDF = async (item: ResumeAnalysis, e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await generatePDF(item);
    } catch (err) {
      console.error('PDF download error:', err);
    }
  };

  // Handle document deletion
  const handleDelete = async (itemId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!user || !db) return;
    if (!window.confirm('Are you sure you want to delete this evaluation history record?')) {
      return;
    }

    setDeletingId(itemId);
    try {
      const path = `users/${user.uid}/analyses/${itemId}`;
      await deleteDoc(doc(db, 'users', user.uid, 'analyses', itemId));
    } catch (err) {
      handleFirestoreError(err, OperationType.DELETE, `users/${user.uid}/analyses/${itemId}`);
    } finally {
      setDeletingId(null);
    }
  };

  // Filtered & Sorted History List
  const filteredHistory = useMemo(() => {
    return history
      .filter((item) => {
        const ats = item.atsScore ?? item.overallScore ?? 75;
        const title = (item.resumeTitle || '').toLowerCase();
        const target = (item.targetJobTitle || '').toLowerCase();
        const summary = (item.resumeSummary || item.summary || '').toLowerCase();
        const q = searchQuery.toLowerCase().trim();

        const matchesSearch =
          !q ||
          title.includes(q) ||
          target.includes(q) ||
          summary.includes(q) ||
          (item.detectedSkills && item.detectedSkills.some((s) => s.toLowerCase().includes(q)));

        let matchesScore = true;
        if (scoreFilter === 'high') matchesScore = ats >= 80;
        else if (scoreFilter === 'good') matchesScore = ats >= 60 && ats < 80;
        else if (scoreFilter === 'low') matchesScore = ats < 60;

        return matchesSearch && matchesScore;
      })
      .sort((a, b) => {
        const scoreA = a.atsScore ?? a.overallScore ?? 75;
        const scoreB = b.atsScore ?? b.overallScore ?? 75;
        const dateA = new Date(a.createdAt || 0).getTime();
        const dateB = new Date(b.createdAt || 0).getTime();

        if (sortBy === 'newest') return dateB - dateA;
        if (sortBy === 'oldest') return dateA - dateB;
        if (sortBy === 'highest') return scoreB - scoreA;
        if (sortBy === 'lowest') return scoreA - scoreB;
        return 0;
      });
  }, [history, searchQuery, scoreFilter, sortBy]);

  if (!user) return null;

  return (
    <div id="resume-history-page" className="space-y-6 max-w-7xl mx-auto pb-12">
      {/* Page Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white p-6 sm:p-8 rounded-[24px] border border-gray-100 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4"
      >
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-blue-50 text-[#2563EB] flex items-center justify-center shrink-0">
            <History className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-2xl font-bold text-gray-900 tracking-tight">Analysis History</h2>
              <span className="text-xs font-semibold px-2.5 py-0.5 rounded-full bg-blue-50 text-[#2563EB] border border-blue-100">
                {history.length} {history.length === 1 ? 'Record' : 'Records'}
              </span>
            </div>
            <p className="text-xs text-gray-500 mt-1">
              Browse, search, and download your previous ATS resume evaluations.
            </p>
          </div>
        </div>
      </motion.div>

      {/* Search and Filters Bar */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="bg-white p-5 rounded-[24px] border border-gray-100 shadow-xs space-y-4"
      >
        <div className="flex flex-col lg:flex-row items-stretch lg:items-center gap-4">
          {/* Search Input */}
          <div className="relative flex-1">
            <Search className="w-4 h-4 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
            <input
              id="history-search-input"
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by resume title, job title, skills, or keywords..."
              className="w-full pl-11 pr-10 py-2.5 bg-gray-50/80 hover:bg-gray-50 border border-gray-200 rounded-2xl text-xs text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#2563EB]/20 focus:border-[#2563EB] transition-all"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 p-1"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            )}
          </div>

          {/* Filter Pills & Sort Select */}
          <div className="flex flex-wrap items-center gap-3">
            {/* Score Filters */}
            <div className="flex items-center gap-1 bg-gray-100/80 p-1 rounded-2xl">
              <button
                id="filter-score-all"
                onClick={() => setScoreFilter('all')}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                  scoreFilter === 'all'
                    ? 'bg-white text-gray-900 shadow-xs'
                    : 'text-gray-500 hover:text-gray-900'
                }`}
              >
                All
              </button>
              <button
                id="filter-score-high"
                onClick={() => setScoreFilter('high')}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                  scoreFilter === 'high'
                    ? 'bg-emerald-50 text-emerald-700 shadow-xs'
                    : 'text-gray-500 hover:text-emerald-600'
                }`}
              >
                High (80+)
              </button>
              <button
                id="filter-score-good"
                onClick={() => setScoreFilter('good')}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                  scoreFilter === 'good'
                    ? 'bg-amber-50 text-amber-700 shadow-xs'
                    : 'text-gray-500 hover:text-amber-600'
                }`}
              >
                60 - 79
              </button>
              <button
                id="filter-score-low"
                onClick={() => setScoreFilter('low')}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                  scoreFilter === 'low'
                    ? 'bg-rose-50 text-rose-700 shadow-xs'
                    : 'text-gray-500 hover:text-rose-600'
                }`}
              >
                &lt; 60
              </button>
            </div>

            {/* Sort Select */}
            <div className="relative inline-flex items-center">
              <ArrowUpDown className="w-3.5 h-3.5 absolute left-3 text-gray-400 pointer-events-none" />
              <select
                id="history-sort-select"
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value as any)}
                className="pl-8 pr-8 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-semibold text-gray-700 focus:outline-none focus:border-[#2563EB] cursor-pointer appearance-none"
              >
                <option value="newest">Newest First</option>
                <option value="oldest">Oldest First</option>
                <option value="highest">Highest Score</option>
                <option value="lowest">Lowest Score</option>
              </select>
            </div>
          </div>
        </div>
      </motion.div>

      {/* History Grid / List */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Skeleton variant="card" />
          <Skeleton variant="card" />
          <Skeleton variant="card" />
        </div>
      ) : filteredHistory.length === 0 ? (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="bg-white p-12 rounded-[24px] border border-gray-100 text-center space-y-4"
        >
          <div className="w-12 h-12 rounded-2xl bg-gray-50 text-gray-400 mx-auto flex items-center justify-center">
            <AlertCircle className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-base font-bold text-gray-900">No evaluations found</h3>
            <p className="text-xs text-gray-500 max-w-sm mx-auto">
              {searchQuery || scoreFilter !== 'all'
                ? 'No evaluations match your search and filter criteria. Try resetting filters.'
                : 'You have not uploaded any resumes for evaluation yet. Upload your first resume to view history!'}
            </p>
          </div>
          {(searchQuery || scoreFilter !== 'all') && (
            <button
              onClick={() => {
                setSearchQuery('');
                setScoreFilter('all');
              }}
              className="px-4 py-2 rounded-xl bg-gray-100 text-xs font-semibold text-gray-700 hover:bg-gray-200 transition-colors"
            >
              Clear Search Filters
            </button>
          )}
        </motion.div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <AnimatePresence mode="popLayout">
            {filteredHistory.map((item, index) => {
              const atsScore = item.atsScore ?? item.overallScore ?? 75;
              const uploadDateFormatted = item.createdAt
                ? new Date(item.createdAt).toLocaleDateString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  })
                : 'N/A';

              const analysisDateFormatted = item.createdAt
                ? new Date(item.createdAt).toLocaleString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                  })
                : 'N/A';

              const scoreBadgeClass =
                atsScore >= 80
                  ? 'bg-emerald-50 text-emerald-700 border-emerald-100'
                  : atsScore >= 60
                  ? 'bg-amber-50 text-amber-700 border-amber-100'
                  : 'bg-rose-50 text-rose-700 border-rose-100';

              return (
                <motion.div
                  key={item.id || index}
                  layout
                  initial={{ opacity: 0, y: 15 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  transition={{ duration: 0.25, delay: index * 0.04 }}
                  className="bg-white rounded-[24px] border border-gray-100 p-6 shadow-xs hover:border-gray-200 hover:shadow-md transition-all flex flex-col justify-between space-y-5 group"
                >
                  {/* Top Header info */}
                  <div className="space-y-3">
                    <div className="flex items-start justify-between gap-2">
                      <div className="space-y-1">
                        <span className="text-[11px] font-semibold text-[#2563EB] flex items-center gap-1">
                          <FileText className="w-3.5 h-3.5" />
                          {item.targetJobTitle || 'General Profile'}
                        </span>
                        {/* RESUME NAME */}
                        <h3
                          id={`history-title-${item.id}`}
                          className="text-base font-bold text-gray-900 tracking-tight line-clamp-1 group-hover:text-[#2563EB] transition-colors"
                        >
                          {item.resumeTitle || 'Resume Evaluation'}
                        </h3>
                      </div>

                      {/* ATS SCORE BADGE */}
                      <div
                        id={`history-score-${item.id}`}
                        className={`px-3 py-1.5 rounded-2xl text-xs font-extrabold border flex items-center gap-1 shrink-0 ${scoreBadgeClass}`}
                      >
                        <Award className="w-3.5 h-3.5" />
                        <span>{atsScore}/100</span>
                      </div>
                    </div>

                    {/* DATES: Upload Date & Analysis Date */}
                    <div className="space-y-1 pt-1 border-t border-gray-50 text-[11px] text-gray-500">
                      <div className="flex items-center justify-between">
                        <span className="flex items-center gap-1 text-gray-400">
                          <Calendar className="w-3 h-3" /> Upload Date:
                        </span>
                        <span className="font-medium text-gray-700">{uploadDateFormatted}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="flex items-center gap-1 text-gray-400">
                          <Clock className="w-3 h-3" /> Analysis Date:
                        </span>
                        <span className="font-medium text-gray-700">{analysisDateFormatted}</span>
                      </div>
                    </div>

                    {/* Summary Snippet */}
                    <p className="text-xs text-gray-600 line-clamp-2 leading-relaxed pt-1">
                      {item.resumeSummary || item.summary || 'AI evaluation complete.'}
                    </p>
                  </div>

                  {/* BUTTONS: View, Download PDF, Download Report, Delete */}
                  <div className="pt-3 border-t border-gray-100 flex items-center justify-between gap-1.5">
                    {/* View Button */}
                    <button
                      id={`view-btn-${item.id}`}
                      onClick={() => onSelectAnalysis(item)}
                      className="flex-1 inline-flex items-center justify-center gap-1 px-2.5 py-2 rounded-xl bg-blue-50 hover:bg-blue-100 text-[#2563EB] text-xs font-semibold transition-colors cursor-pointer"
                      title="View full analysis result"
                    >
                      <Eye className="w-3.5 h-3.5" />
                      <span>View</span>
                    </button>

                    {/* Download PDF Button */}
                    <button
                      id={`download-pdf-btn-${item.id}`}
                      onClick={(e) => handleDownloadPDF(item, e)}
                      className="inline-flex items-center justify-center gap-1 px-2.5 py-2 rounded-xl bg-emerald-50 hover:bg-emerald-100 text-emerald-700 text-xs font-semibold transition-colors cursor-pointer border border-emerald-100"
                      title="Download formatted PDF report"
                    >
                      <FileDown className="w-3.5 h-3.5 text-emerald-600" />
                      <span>PDF</span>
                    </button>

                    {/* Download Text Report Button */}
                    <button
                      id={`download-txt-btn-${item.id}`}
                      onClick={(e) => handleDownloadReport(item, e)}
                      className="inline-flex items-center justify-center gap-1 px-2.5 py-2 rounded-xl border border-gray-200 hover:bg-gray-50 text-gray-700 text-xs font-semibold transition-colors cursor-pointer"
                      title="Download text summary report"
                    >
                      <Download className="w-3.5 h-3.5 text-gray-500" />
                      <span className="hidden xl:inline">Text</span>
                    </button>

                    {/* Delete Button */}
                    <button
                      id={`delete-btn-${item.id}`}
                      onClick={(e) => handleDelete(item.id!, e)}
                      disabled={deletingId === item.id}
                      className="p-2 rounded-xl border border-gray-200 hover:bg-rose-50 hover:border-rose-200 text-gray-400 hover:text-rose-600 transition-colors cursor-pointer"
                      title="Delete evaluation record"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      )}
    </div>
  );
};
